version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: admin-template-postgres
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - '5432:5432'
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  redis:
    image: redis:6
    container_name: admin-template-redis
    ports:
      - '6379:6379'
